version: '3'

services:
  httpd:
    build: httpd
    image: ${IMAGE_NS}/magento-httpd
    restart: always
    container_name: ${COMPOSE_PROJECT_NAME}_httpd
    ports:
      - "${HTTPD_PORT_80}:80"
      - "${HTTPD_PORT_443}:443"
    environment:
      - SERVER_NAME
      - PHP_SERVER=${COMPOSE_PROJECT_NAME}_php
      - PHP_PORT
      - WORKDIR
    volumes:
      - ${MAGENTO_VOLUME}:/var/www/html:delegated
    networks:
      - network
  php:
    build:
      context: php
      args:
        - DEPLOY_USER_HOME
        - DEPLOY_USER
        - WORKDIR
    image: ${IMAGE_NS}/magento-php
    restart: always
    container_name: ${COMPOSE_PROJECT_NAME}_php
    volumes:
      - ${MAGENTO_VOLUME}:/var/www/html:delegated
    networks:
      - network
    environment:
      - DEPLOY_USER_HOME
      - DEPLOY_USER
      - WORKDIR
  db:
    build: mysql
    image: ${IMAGE_NS}/magento-db
    restart: always
    container_name: ${COMPOSE_PROJECT_NAME}_db
    networks:
      - network
    ports:
      - "${DB_PORT}:3309"
    volumes:
      - magento-db:/var/lib/mysql
volumes:
  magento-db:
networks:
  network:
